a = input('Digite algo: ')
print('O tpo primitivo desse valor é :', type(a))
print('Só tem espaços? :', a.isspace())
print('É só numerico? :', a.isnumeric())
print('É alfabetico? :', a.isalpha())
print('É alfanumrico? :', a.isalnum())
print('Esta em maiuscula? :', a.isupper())
print('Esta em minuscula? :', a.islower())
print('Esta capitalizada? :', a.istitle())